import { frontendListenerSlot, makeHandlerInvoker, makeListenerCaller } from '../ipc'
import { tauriCreateNewWindow } from './tauriChildWindows'

export const notify = makeListenerCaller('notify')
export const openLoginPage = makeListenerCaller('openLoginPage')
export const openSidInfoPage = makeListenerCaller('openSidInfoPage')
export const openSupportPage = makeListenerCaller('openSupportPage')
export const quit = makeListenerCaller('quit')
export const openDiscordLink = makeListenerCaller('openDiscordLink')
export const openWinePrefixFAQ = makeListenerCaller('openWinePrefixFAQ')
export const openCustomThemesWiki = makeListenerCaller('openCustomThemesWiki')
// D-12 (Phase 34.1 Plan 07): createNewWindow opens a genuine Tauri WebviewWindow --
// renderer-side, per tauriChildWindows.ts's module comment. Phase 35 plan 17 collapsed
// the Electron-branch fallback (`makeListenerCaller('createNewWindow')`), which is
// unreachable now that the Tauri shell is the only shell. `showAboutWindow` sat beside
// it until quick `260905-d33` made About an in-app modal and deleted the window.
export const createNewWindow = (url: string) => tauriCreateNewWindow(url)
export const readConfig = makeHandlerInvoker('readConfig')
export const isLoggedIn = makeHandlerInvoker('isLoggedIn')
export const writeConfig = makeHandlerInvoker('writeConfig')
export const kill = makeHandlerInvoker('kill')
export const abort = makeListenerCaller('abort')
export const getUserInfo = makeHandlerInvoker('getUserInfo')
export const getAmazonUserInfo = makeHandlerInvoker('getAmazonUserInfo')
export const syncSaves = makeHandlerInvoker('syncSaves')
export const getDefaultSavePath = makeHandlerInvoker('getDefaultSavePath')
export const getGameInfo = makeHandlerInvoker('getGameInfo')
export const getAchievements = makeHandlerInvoker('getAchievements')
export const getExtraInfo = makeHandlerInvoker('getExtraInfo')
export const getLaunchOptions = makeHandlerInvoker('getLaunchOptions')
export const getPrivateBranchPassword = makeHandlerInvoker('getPrivateBranchPassword')
export const setPrivateBranchPassword = makeHandlerInvoker('setPrivateBranchPassword')
// REDmod integration
export const getAvailableCyberpunkMods = makeHandlerInvoker('getAvailableCyberpunkMods')
export const setCyberpunModConfig = makeHandlerInvoker('setCyberpunkModConfig')
export const getGameSettings = makeHandlerInvoker('getGameSettings')
export const getInstallInfo = makeHandlerInvoker('getInstallInfo')
export const runWineCommand = makeHandlerInvoker('runWineCommand')
export const runWineCommandForGame = makeHandlerInvoker('runWineCommandForGame')
export const onConnectivityChanged = frontendListenerSlot('connectivity-changed')
export const getConnectivityStatus = makeHandlerInvoker('get-connectivity-status')
export const setConnectivityOnline = makeListenerCaller('set-connectivity-online')
export const connectivityChanged = makeListenerCaller('connectivity-changed')
export const isNative = makeHandlerInvoker('isNative')
export const getThemeCSS = makeHandlerInvoker('getThemeCSS')
export const getCustomThemes = makeHandlerInvoker('getCustomThemes')
export const getCustomCSS = makeHandlerInvoker('getCustomCSS')
export const getLoginBackground = makeHandlerInvoker('getLoginBackground')
export const getGogDiscounts = makeHandlerInvoker('getGogDiscounts')
export const setTitleBarOverlay = makeListenerCaller('setTitleBarOverlay')
export const isGameAvailable = makeHandlerInvoker('isGameAvailable')
