/**
 * Unit coverage for `parseWinetricksMetadata` and `deriveNeedsGuiVerbs`
 * (45-04). Both are pure functions over the script's own text -- no wine
 * invocation, no fs, no electron -- per D-19 and D-17.
 *
 * FIXTURE RULE. `winetricks-20260125-next.metadata.sh` is a committed,
 * reproducible excerpt of the real pinned script (sha256
 * f35c29737ca08a583569e6a3752d52fbe23333c5acfad5f16c4177d25eaf3f4b),
 * regenerated by the awk commands recorded in its own header comment --
 * never hand-edited. It carries every `w_metadata` block (567 verbs) plus
 * the verbatim `load_<name>()` bodies for the 11 verbs these tests need
 * (the six real `w_download_manual` callers, plus `gdiplus_winxp` and
 * `protectionid` -- both set `media="manual_download"` but call ordinary
 * `w_download` -- and `fontxplorer` / `ubisoftconnect`, both silent-install
 * flag verbs, plus `d3dx9`).
 */
import { readFileSync } from 'fs'
import { join } from 'path'
import { parseWinetricksMetadata, deriveNeedsGuiVerbs } from '../metadata'

const FIXTURE_SCRIPT = readFileSync(
  join(__dirname, 'fixtures', 'winetricks-20260125-next.metadata.sh'),
  'utf8'
)

const NEEDS_GUI_VERBS = [
  '3dmark03',
  '3dmark06',
  'foobar2000',
  'stalker_pripyat_bench',
  'unigine_heaven',
  'utorrent'
]

describe('parseWinetricksMetadata', () => {
  it('extracts title/publisher/year/conflicts from a synthetic w_metadata block', () => {
    const scriptText =
      'w_metadata foo dlls \\\n' +
      '    title="Foo (a,b)" \\\n' +
      '    publisher="Acme" \\\n' +
      '    year="2001" \\\n' +
      '    conflicts="bar baz"\n'
    const result = parseWinetricksMetadata(scriptText)
    expect(result.get('foo')).toEqual({
      verb: 'foo',
      category: 'dlls',
      title: 'Foo (a,b)',
      publisher: 'Acme',
      year: '2001',
      conflicts: ['bar', 'baz']
    })
  })

  it('ignores a `title_<lang>=` continuation line -- only `title=` populates title', () => {
    const scriptText =
      'w_metadata foo settings \\\n' +
      '    title_bg="Чуждица" \\\n' +
      '    title="English title"\n'
    const result = parseWinetricksMetadata(scriptText)
    expect(result.get('foo')?.title).toBe('English title')
  })

  it('parses a header-only block, and a blank or unquoted-tail continuation line neither throws nor ends the parse early', () => {
    const scriptText =
      'w_metadata good settings \\\n' +
      '    title="Always true" \\\n' +
      '\n' +
      '    installed_file1="${W_SYSTEM32_DLLS_WIN}"/l3codeca.acm\n' +
      'w_metadata bad settings \\\n' +
      '    title="Always false"\n'
    expect(() => parseWinetricksMetadata(scriptText)).not.toThrow()
    const result = parseWinetricksMetadata(scriptText)
    expect(result.get('good')?.title).toBe('Always true')
    expect(result.get('bad')?.title).toBe('Always false')
  })

  describe('against the committed fixture', () => {
    it('parses all 567 verbs with the researched category counts', () => {
      const result = parseWinetricksMetadata(FIXTURE_SCRIPT)
      expect(result.size).toBe(567)
      const counts: Record<string, number> = {}
      for (const meta of result.values()) {
        counts[meta.category] = (counts[meta.category] ?? 0) + 1
      }
      expect(counts).toEqual({
        dlls: 328,
        fonts: 42,
        settings: 132,
        apps: 57,
        benchmarks: 8
      })
    })

    it('preserves script order (foobar2000 insertion position precedes utorrent)', () => {
      const result = parseWinetricksMetadata(FIXTURE_SCRIPT)
      const verbsInOrder = [...result.keys()]
      expect(verbsInOrder.indexOf('foobar2000')).toBeLessThan(
        verbsInOrder.indexOf('utorrent')
      )
    })

    it('gdiplus_winxp: publisher Microsoft, year 2009, media manual_download', () => {
      const result = parseWinetricksMetadata(FIXTURE_SCRIPT)
      expect(result.get('gdiplus_winxp')).toMatchObject({
        publisher: 'Microsoft',
        year: '2009',
        media: 'manual_download'
      })
    })

    it('vcrun2019: conflicts contains vcrun2022', () => {
      const result = parseWinetricksMetadata(FIXTURE_SCRIPT)
      expect(result.get('vcrun2019')?.conflicts).toContain('vcrun2022')
    })
  })
})

describe('deriveNeedsGuiVerbs', () => {
  it('against the committed fixture, returns exactly the six w_download_manual callers', () => {
    const result = deriveNeedsGuiVerbs(FIXTURE_SCRIPT)
    expect([...result].sort()).toEqual([...NEEDS_GUI_VERBS].sort())
  })

  it('does not include gdiplus_winxp or protectionid (media=manual_download, ordinary w_download)', () => {
    const result = deriveNeedsGuiVerbs(FIXTURE_SCRIPT)
    expect(result.has('gdiplus_winxp')).toBe(false)
    expect(result.has('protectionid')).toBe(false)
  })

  it('does not include fontxplorer or ubisoftconnect (silent-install flags, not w_download_manual)', () => {
    const result = deriveNeedsGuiVerbs(FIXTURE_SCRIPT)
    expect(result.has('fontxplorer')).toBe(false)
    expect(result.has('ubisoftconnect')).toBe(false)
  })

  it('non-vacuity: rewriting load_foobar2000 to call w_download removes foobar2000 from the derived set', () => {
    const sabotaged = FIXTURE_SCRIPT.replace(
      /w_download_manual https:\/\/www\.foobar2000\.org\/download/,
      'w_download https://www.foobar2000.org/download'
    )
    expect(sabotaged).not.toBe(FIXTURE_SCRIPT)
    const result = deriveNeedsGuiVerbs(sabotaged)
    expect(result.has('foobar2000')).toBe(false)
    expect([...result].sort()).toEqual(
      NEEDS_GUI_VERBS.filter((v) => v !== 'foobar2000').sort()
    )
  })
})
