#!/usr/bin/env node
// Spike 023, task 3(d): the miniature build pipeline, argv-form spawns only
// (T-24-06, never a shell string), mirroring meta/buildSidecarSea.ts:
//   1. resolve build-time constants (lzma-native's real package root/prebuild
//      filename, the fixture bytes) and bake them into two generated CJS
//      files binding-shim.cjs / sea-main.cjs require() plainly
//   2. esbuild sea-main.cjs -> build/sea-main.js
//   3. esbuild sea-worker-entry.cjs -> build/worker.js (node-gyp-build
//      aliased to binding-shim.cjs)
//   4. write sea-config.json with exactly two assets: worker.js,
//      lzma_native.node
//   5. node --experimental-sea-config sea-config.json -> build/sidecar-prep.blob
//   6. copy process.execPath -> build/spike-sea-bin
//   7. darwin: codesign --remove-signature
//   8. postject inject the blob (NODE_SEA_BLOB, sentinel fuse, darwin:
//      --macho-segment-name NODE_SEA)
//   9. darwin: codesign --sign -
//
// Throws loudly (COMPILE GATE FAILED, matching buildSidecarSea.ts's own
// discipline) on any non-zero exit or missing output file.

import { spawn } from 'node:child_process'
import { createHash } from 'node:crypto'
import {
  existsSync,
  mkdirSync,
  copyFileSync,
  readFileSync,
  writeFileSync,
  chmodSync
} from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = join(__dirname, '..', '..', '..')
const require = createRequire(import.meta.url)

const BUILD_DIR = join(__dirname, 'build')
const SEA_BUNDLE_PATH = join(BUILD_DIR, 'sea-main.js')
const SEA_WORKER_BUNDLE_PATH = join(BUILD_DIR, 'worker.js')
const SEA_CONFIG_PATH = join(BUILD_DIR, 'sea-config.json')
const SEA_BLOB_PATH = join(BUILD_DIR, 'sidecar-prep.blob')
const SEA_BIN_PATH = join(BUILD_DIR, 'spike-sea-bin')

// Official/fixed sentinel fuse string -- do not alter
// (https://nodejs.org/api/single-executable-applications.html), mirrors
// meta/buildSidecarSea.ts's own SENTINEL_FUSE constant verbatim.
const SENTINEL_FUSE = 'NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2'
// SEA asset key literal -- MUST match binding-shim.cjs's SEA_ASSET_KEY.
const NATIVE_ADDON_ASSET_KEY = 'lzma_native.node'
// Task 2's observed fact: the real prebuild filename is node.napi.node, NOT
// the lzma_native.node the plan/RESEARCH.md assumed (that string is only
// the SEA asset key above, independent of the source filename).
const NATIVE_NODE_FILENAME = 'node.napi.node'

function spawnArgv(command, args) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, { stdio: ['ignore', 'pipe', 'pipe'] })
    let stdout = ''
    let stderr = ''
    child.stdout?.on('data', (d) => (stdout += d.toString()))
    child.stderr?.on('data', (d) => (stderr += d.toString()))
    child.on('error', reject)
    child.on('close', (code) => resolve({ code, stdout, stderr }))
  })
}

function resolveEsbuildCli() {
  try {
    return require.resolve('esbuild/bin/esbuild', { paths: [REPO_ROOT] })
  } catch (error) {
    throw new Error(
      `COMPILE GATE FAILED: cannot resolve esbuild/bin/esbuild -- is it installed? (${error.message})`
    )
  }
}

function resolvePostjectCli() {
  try {
    return require.resolve('postject/dist/cli.js', { paths: [REPO_ROOT] })
  } catch (error) {
    throw new Error(
      `COMPILE GATE FAILED: cannot resolve postject/dist/cli.js -- is it installed? (${error.message})`
    )
  }
}

/** Step 1a: resolve lzma-native's real package root on this machine and
 *  write it (plus the observed prebuild filename) as a plain-data CJS
 *  module -- binding-shim.cjs requires this directly. See binding-shim.cjs's
 *  own header comment for WHY this cannot be derived from __dirname once
 *  bundled. */
function writeResolvedPaths() {
  const lzmaNativePkgJson = require.resolve('lzma-native/package.json', {
    paths: [__dirname]
  })
  const lzmaNativePkgRoot = dirname(lzmaNativePkgJson)
  const content =
    `// GENERATED by build-sea.mjs -- do not edit by hand.\n` +
    `module.exports = ${JSON.stringify(
      {
        LZMA_NATIVE_PKG_ROOT: lzmaNativePkgRoot,
        NATIVE_NODE_FILENAME
      },
      null,
      2
    )}\n`
  writeFileSync(join(__dirname, 'resolved-paths.generated.cjs'), content)
  console.log(`[build-sea] wrote resolved-paths.generated.cjs (root=${lzmaNativePkgRoot})`)
  return lzmaNativePkgRoot
}

/** Step 1b: embed the task-2 fixture (real VZ chunk bytes + expected sha1)
 *  as a base64 string literal inside a generated CJS module -- sea-main.cjs
 *  requires this directly, so the fixture ships inside the SEA blob's MAIN
 *  script rather than as a third sea-config asset (the plan's acceptance
 *  criteria require exactly two asset keys: worker.js, lzma_native.node). */
function writeEmbeddedFixture() {
  const fixturePath = join(__dirname, 'fixtures', 'real-vz-chunk.bin')
  const fixtureMetaPath = join(__dirname, 'fixtures', 'real-vz-chunk.meta.json')
  if (!existsSync(fixturePath) || !existsSync(fixtureMetaPath)) {
    throw new Error(
      `Missing fixture at ${fixturePath} -- run make-chunk.mjs first (task 2d).`
    )
  }
  const bytes = readFileSync(fixturePath)
  const meta = JSON.parse(readFileSync(fixtureMetaPath, 'utf8'))
  const content =
    `// GENERATED by build-sea.mjs -- do not edit by hand.\n` +
    `module.exports = ${JSON.stringify(
      {
        vzChunkBase64: bytes.toString('base64'),
        expectedSha1: meta.sha1Uncompressed
      },
      null,
      2
    )}\n`
  writeFileSync(join(__dirname, 'fixture-embedded.generated.cjs'), content)
  console.log(
    `[build-sea] wrote fixture-embedded.generated.cjs (${bytes.length} bytes, sha1=${meta.sha1Uncompressed})`
  )
}

async function bundleSeaMain() {
  mkdirSync(BUILD_DIR, { recursive: true })
  const esbuildCli = resolveEsbuildCli()
  const args = [
    '--bundle',
    '--platform=node',
    '--target=node22',
    '--format=cjs',
    `--outfile=${SEA_BUNDLE_PATH}`,
    join(__dirname, 'sea-main.cjs')
  ]
  const result = await spawnArgv(esbuildCli, args)
  if (result.code !== 0) {
    throw new Error(`COMPILE GATE FAILED: esbuild sea-main bundle exited ${result.code}:\n${result.stderr}`)
  }
  if (!existsSync(SEA_BUNDLE_PATH)) {
    throw new Error('COMPILE GATE FAILED: esbuild exited 0 but sea-main.js was not emitted')
  }
  console.log(`[build-sea] bundled sea-main.cjs -> ${SEA_BUNDLE_PATH}`)
}

async function bundleWorker() {
  mkdirSync(BUILD_DIR, { recursive: true })
  const esbuildCli = resolveEsbuildCli()
  const args = [
    '--bundle',
    '--platform=node',
    '--target=node22',
    '--format=cjs',
    `--alias:node-gyp-build=${join(__dirname, 'binding-shim.cjs')}`,
    `--outfile=${SEA_WORKER_BUNDLE_PATH}`,
    join(__dirname, 'sea-worker-entry.cjs')
  ]
  const result = await spawnArgv(esbuildCli, args)
  if (result.code !== 0) {
    throw new Error(`COMPILE GATE FAILED: esbuild worker bundle exited ${result.code}:\n${result.stderr}`)
  }
  if (!existsSync(SEA_WORKER_BUNDLE_PATH)) {
    throw new Error('COMPILE GATE FAILED: esbuild exited 0 but worker.js was not emitted')
  }
  console.log(`[build-sea] bundled sea-worker-entry.cjs -> ${SEA_WORKER_BUNDLE_PATH}`)
}

function writeSeaConfig(lzmaNativePkgRoot) {
  const nativeAddonPath = join(
    lzmaNativePkgRoot,
    'prebuilds',
    `${process.platform}-${process.arch}`,
    NATIVE_NODE_FILENAME
  )
  if (!existsSync(nativeAddonPath)) {
    throw new Error(`COMPILE GATE FAILED: no prebuild at ${nativeAddonPath}`)
  }
  const config = {
    main: SEA_BUNDLE_PATH,
    output: SEA_BLOB_PATH,
    disableExperimentalSEAWarning: true,
    assets: {
      'worker.js': SEA_WORKER_BUNDLE_PATH,
      [NATIVE_ADDON_ASSET_KEY]: nativeAddonPath
    }
  }
  writeFileSync(SEA_CONFIG_PATH, JSON.stringify(config, null, 2))
  console.log(`[build-sea] wrote sea-config.json (assets: ${Object.keys(config.assets).join(', ')})`)
}

async function generateSeaBlob() {
  const result = await spawnArgv(process.execPath, ['--experimental-sea-config', SEA_CONFIG_PATH])
  if (result.code !== 0) {
    throw new Error(
      `COMPILE GATE FAILED: node --experimental-sea-config exited ${result.code}:\n${result.stderr}`
    )
  }
  if (!existsSync(SEA_BLOB_PATH)) {
    throw new Error('COMPILE GATE FAILED: --experimental-sea-config exited 0 but no blob was emitted')
  }
  console.log(`[build-sea] generated SEA blob -> ${SEA_BLOB_PATH}`)
}

function copyBaseBinary() {
  copyFileSync(process.execPath, SEA_BIN_PATH)
  chmodSync(SEA_BIN_PATH, 0o755)
  console.log(`[build-sea] copied base binary (${process.execPath}) -> ${SEA_BIN_PATH}`)
}

async function codesignStep(args) {
  const result = await spawnArgv('codesign', args)
  if (result.code !== 0) {
    throw new Error(`COMPILE GATE FAILED: codesign ${args.join(' ')} exited ${result.code}:\n${result.stderr}`)
  }
}

async function injectBlob() {
  const postjectCli = resolvePostjectCli()
  const args = [postjectCli, SEA_BIN_PATH, 'NODE_SEA_BLOB', SEA_BLOB_PATH, '--sentinel-fuse', SENTINEL_FUSE]
  if (process.platform === 'darwin') {
    args.push('--macho-segment-name', 'NODE_SEA')
  }
  const result = await spawnArgv(process.execPath, args)
  if (result.code !== 0) {
    throw new Error(`COMPILE GATE FAILED: postject exited ${result.code}:\n${result.stderr}\n${result.stdout}`)
  }
  console.log(`[build-sea] postject injected blob into ${SEA_BIN_PATH}`)
}

async function main() {
  console.log(`[build-sea] platform=${process.platform} arch=${process.arch} node=${process.version}`)

  const lzmaNativePkgRoot = writeResolvedPaths()
  writeEmbeddedFixture()

  await bundleSeaMain()
  await bundleWorker()

  writeSeaConfig(lzmaNativePkgRoot)
  await generateSeaBlob()

  copyBaseBinary()

  if (process.platform === 'darwin') {
    await codesignStep(['--remove-signature', SEA_BIN_PATH])
  }

  await injectBlob()

  if (process.platform === 'darwin') {
    await codesignStep(['--sign', '-', SEA_BIN_PATH])
  }

  const sha256 = createHash('sha256').update(readFileSync(SEA_BIN_PATH)).digest('hex')
  console.log(`[build-sea] DONE -- ${SEA_BIN_PATH} (sha256=${sha256})`)
}

main().catch((error) => {
  console.error('[build-sea] FAILED', error)
  process.exit(1)
})
